name: STM32 Cppcheck PDF Report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cppcheck wkhtmltopdf enscript ghostscript

    - name: Verify files exist
      run: |
        ls -R OBD2/CM7/Core/Src
        ls -R OBD2/CM7/TouchGFX/gui/src

    - name: Run cppcheck
      run: |
        cppcheck --enable=all --inconclusive --std=c11 \
        OBD2/CM7/Core/Src/main.c \
        OBD2/CM7/Core/Src/freertos.c \
        OBD2/CM7/TouchGFX/gui/src \
        --xml --xml-version=2 2> cppcheck-report.xml

    - name: Generate simple text report
      run: |
        cppcheck --enable=all --inconclusive --std=c11 \
        OBD2/CM7/Core/Src/main.c \
        OBD2/CM7/Core/Src/freertos.c \
        OBD2/CM7/TouchGFX/gui/src > report.txt

    - name: Create report folder
      run: mkdir -p report

    - name: Convert text report to PDF
      run: |
        enscript report.txt -o - | ps2pdf - report/cppcheck-report.pdf

    - name: Upload PDF Artifact
      uses: actions/upload-artifact@v4
      with:
        name: cppcheck-pdf-report
        path: report/cppcheck-report.pdf
